Repository Turbo87/ember-cli-deploy-ftp, pull requests merged in 2021-06, with the labels that each got.

#9 Allow to upload via SFTP
  index.js
  package.json
Labels: enhancement

#10 Drop support for Node.js 10 and below
  .travis.yml
  package.json
Labels: breaking

#11 Modernize plugin code
  index.js
Labels: internal

#12 Use `pnpm` to install dependencies
  .npmignore
  .travis.yml
  pnpm-lock.yaml
Labels: internal

#13 Adjust ignore files
  .gitignore
  .npmignore
Labels: internal
